name: Publish CareFusion Database Documentation

on:
  push:
    branches:
      - "**"
      - master

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: "zulu"

concurrency:
  group: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref_to_publish || github.ref }}
  cancel-in-progress: false

jobs:
  generate-documentation:
    environment:
      name: github-pages
    name: Generate Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: carefusion_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: carefusion
        ports:
          - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.ref_to_publish || github.ref}}
          fetch-depth: 0

      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          distribution: ${{env.JAVA_DISTRIBUTION}}
          java-version: ${{env.JAVA_VERSION}}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3


#      - name: Config Artifactory
      - name: Setup Liquibase and Update
        uses: liquibase-github-actions/update@v4.29.1
        with:
          changelogFile: "schema/db-changlog.xml"
          url: "jdbc:postgresql://localhost:5432/carefusion_development"
          defaultSchemaName: "carefusion_development"
          password: "carefusion"
          username: "postgres"

