name: Publish CareFusion Database Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: "zulu"

concurrency:
  group: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref_to_publish || github.ref }}
  cancel-in-progress: false

jobs:
  generate-documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: carefusion_development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: carefusion
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.ref_to_publish || github.ref}}
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Liquibase and Update
        uses: liquibase-github-actions/update@v4.29.1
        with:
          changelogFile: "schema/db-changelog.xml"
          url: "jdbc:postgresql://postgres:5432/carefusion_development"
          password: "carefusion"
          username: "postgres"
          driver: "org.postgresql.Driver"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

#      - name: Build SchemaSpy Files
#        run: ./gradlew schemaspy
      - name: Run SchemaSpy
        uses: tj-actions/schemaspy@v2
        with:
          host: postgres
          port: 5432
          database_name: carefusion_development
          database_type: pgsql
          user: postgres
          password: carefusion
          all: true
          output_dir: schemaspyPages

      - name: Push SchemaSpy webpage to SchemaSpy Repository
        uses: lubu12/copy-files-to-repository@v1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'schemaspyPages/'
          destination-username: 'DoubleHaoDev'
          destination-repository: 'carefusion-schemaSpy'
          destination-branch: 'main'
